### ISSUE TITLE
Is there a way to specify sap-client in SCTS_CLOUD_API_ODATA_SRV?

### ISSUE THREAD

**Issue by ksaito1125** [SAP/python-pyodata#138]
Initializing pyodata.Client using the code below will result in an authentication error.
I want to connect to a 510 client. Can I specify sap-client = 510 to connect to in pyodata.Client?

```
>>> import requests, urllib3
>>> from pyodata.exceptions import PyODataException, HttpError
>>> import pyodata
>>> urllib3.disable_warnings()
>>> SERVICE_URL = 'https://' + server + '/sap/opu/odata/sap/SCTS_CLOUD_API_ODATA_SRV'
>>> session = requests.Session()
>>> session.verify = False
>>> session.auth = (user, passwd)
>>> try:
...     client = pyodata.Client(SERVICE_URL, session)
... except HttpError as e:
...     e.response.status_code
...     e.response.headers['set-cookie']
... 
401
'sap-usercontext=sap-client=951; path=/'
>>> 
```

**Comment by ksaito1125** [comment]
I tried running it with curl.

```
$ curl -u $USER -k -I https://$SERVER/sap/opu/odata/sap/SCTS_CLOUD_API_ODATA_SRV/$metadata
HTTP/2 401 
set-cookie: sap-usercontext=sap-client=951; path=/
content-type: text/html; charset=utf-8
content-length: 9321
sap-system: SD1
www-authenticate: Basic realm="SAP NetWeaver Application Server [SD1/951]"
sap-server: true
sap-perf-fesrec: 10227.000000
```

This is the same as what is being done below.
https://github.com/SAP/python-pyodata/blob/1.7.0/pyodata/client.py#L14

I can connect to the correct client by specifying sap-client.

```
$ curl -u $USER -k -I https://$SERVER/sap/opu/odata/sap/SCTS_CLOUD_API_ODATA_SRV/$metadata?sap-client=510
HTTP/2 200 
set-cookie: sap-usercontext=sap-client=510; path=/
set-cookie: SAP_SESSIONID_SD1_510=*******; path=/; secure; HttpOnly
content-type: text/html
content-length: 0
sap-processing-info: ODataBEP=,crp=,RAL=,st=,MedCacheHub=,codeployed=,softstate=
sap-server: true
sap-perf-fesrec: 41539.000000
```

Is there a way to specify sap-client in pyodata.Client?

**Comment by phanak-sap** [comment]
Hi @ksaito1125.
I understand what are you trying to achieve, but I believe you can do it even now without the necessity of changes on the pyodata side. 

In the PR you updated just .get() for initial metadata, but subsequently, every other request, be it GET, POST, PATCH etc. would need this parameter as well to be working as you expecting on target SAP system.

Since what you want is essentially `param = {'sap-client': sap_client}` in every requests call, you should be able to set it up on the `requests.Session()` object, that you need to pass to pyodata instance initialization anyway.

I think the Session.params is exactly for that, so there should not be need for any PR to pyodata.
https://requests.readthedocs.io/en/latest/api/#requests.Session.params

Please try it out and comment if that solves your problem.

Petr

**Comment by ksaito1125** [comment]
Hello @phanak-sap

Your point is correct.
I was able to confirm that it works with the code below.
I appreciate it very much.

```
>>> import requests
>>> import pyodata
>>> session = requests.Session()
>>> session.auth = (user, passwd)
>>> param = {'sap-client': '510'}
>>> session.params = param
>>> client = pyodata.Client(endpoint, session)
>>> transports = client.entity_sets.Transports.get_entities()
>>> tr = transports.filter("Id eq 'SD1K903304'").execute()
>>> tr
[('SD1K903304')]
>>> 
```

**Comment by phanak-sap** [comment]
@ksaito1125 Thanks for checking out my hypothesis. If you would have time, could you please create PR with update of documentation and the sample code (IMHO good enough for the line `client = pyodata.Client(endpoint, session)` in your sample). Since you came into this problem I grant you the honors :)

I guess best it to add new block to  docs/usage/initialization.rst
