### ISSUE TITLE
Error while parsing Dynamics365 metadata

### ISSUE THREAD

**Issue by ultrabug** [SAP/python-pyodata#140]
I get this error while trying to access a Dynamics365 service URL:

```
PyODataParserError("Type None is not valid as underlying type for EnumType - must be one of {'Edm.Byte': [0, 255], 'Edm.Int16': [-32768, 32767], 'Edm.Int32': [-2147483648, 2147483647], 'Edm.Int64': [-9223372036854775808, 9223372036854775807], 'Edm.SByte': [-128, 127]}")
```

How can we investigate the culprit of this please?

Cheers and thanks for your work

**Comment by phanak-sap** [comment]
Hi @ultrabug.

1. Are you sure you are trying to connect to Odata V2 service (and not V3/V4, which protocol versions are not supported yet?)
2. With such generic issue, there is nothing much to investigate on your side really. Could you update the issue / post as Gist the $metadata from the service? Since you can initialize the pyodata with $metadata as local file, this would at least create something reproducible locally - see https://pyodata.readthedocs.io/en/latest/usage/initialization.html#get-the-service-with-local-metadata. Since the metadata parameter takes stream of bytes, you could even have as a Gist simple python script that reproduces the bug.

Nothing to really do on our side for the moment to be frank, need more info.

Cheers to you as well :)

**Comment by ultrabug** [comment]
Thanks for your reply @phanak-sap indeed I'm trying to reach a V4 Odata service :(

I didn't realize that this lib didn't support it (yet?!!) Thanks

**Comment by phanak-sap** [comment]
Not yet, but hopefully in the future yes.. we got stuck a bit. Watch #39 for closure.
