### ISSUE TITLE
feature: Add async networking libraries support 

### ISSUE THREAD

**Issue by Albo90** [SAP/python-pyodata#208]
TOP LEVEL FEATURE TASK LIST:

- [x] create stable feature branch feature-branch - [async-feature](https://github.com/SAP/python-pyodata/tree/async-feature)
- [x] support for async networking - aiohttp.Client - client.py, service.py #210
- [x] check httpx package as networking client; should have sync and async API as well. If yes, update tests to have integration testing of requests (sync), aiohttp (async) and httpx (sync, async) packages
- [x] cover httpx async tests as well
- [x] documentation - https://github.com/SAP/python-pyodata/pull/266
- [x] integration to master - https://github.com/SAP/python-pyodata/pull/225
- [x] release - in version 1.10.0

Hi, 
I used this library recently, it's fantastic very convenient but it doesn't support **async pattern**. 
I and my collegue modified the library to support aiohttp, this is the link: https://github.com/Albo90/python-pyodata/tree/async_python
If you are interested, we can collaborate to integrate it in your project.
We are going to add test and more documentation in a couple of days.  

Thanks

**Comment by filak-sap** [comment]
Impressive. Unfortunately, since you copied all files, I cannot see the needed changes. Can you somehow summarize what needs to be changed?

**Comment by Albo90** [comment]
> Impressive. Unfortunately, since you copied all files, I cannot see the needed changes. Can you somehow summarize what needs to be changed?

Hi filak-sap, 
we had to create a bit of redundancy for our modifications otherwise it's really difficult for us to integragate async.  I try to describe them grouping for file. 

**async_client**
1) Definition of _new_ method accord to async strategy.
2) Definition of _fetch_metadata with get implementation accord to async.

**AsyncService**
1) Modification of execute method into OdataHttpRequest, we use "async with" to create request and build response in aim to avoid excessive ridefionition of project structure. 
2) Modification of http_get method. 

If you want, we can make a reasoning to build other ways of integration

**Comment by filak-sap** [comment]
Is there a way how to avoid huge code duplications?

**Comment by Albo90** [comment]
> Is there a way how to avoid huge code duplications?

Yes, in my option there is possibility to avoid creation of files (async_client, asyncService) rebuilding the existent methods.

**Comment by Albo90** [comment]
@filak-sap we published a new version without duplication. The version is in this branch:   https://github.com/Albo90/python-pyodata/tree/no_duplication_v1. The library has a little syntax changement when it is used with async (pay attention to method getattr in example).

**Sync version:** 
```python
import requests
from pyodata.client import Client

client = Client('http://example.com', requests)
entities = client.entity_sets.resource.get_entities().execute()
for entity in entities:
      print(entity.attr_name)

print(entities)
```
**Async version:**

```python
import asyncio
import aiohttp
from pyodata.client import Client

async def main():
    async with aiohttp.ClientSession() as client:
        service = await Client.build_async_client('http://example.com', client)
        entities = await service.entity_sets.resource.get_entities().select('key').async_execute()
        for entity in entities:
            attr_name = await entity.getattr('attr_name')
            print(attr_name)
        return entities


async_entities = asyncio.run(main())
print(async_entities)
```

**Comment by phanak-sap** [comment]
Support of both requests lib and aiohttp lib is definitely a great idea. I had it on my personal backlog for "experiment someday", so nice to see it done and working :) Great job even just as a submitted proposal.

I had read through the issue comments and the commits:
https://github.com/Albo90/python-pyodata/commit/543d17535dc5c4a30d38411a14690550f580c4db
https://github.com/Albo90/python-pyodata/commit/00ad1dc4feb3b0ca779a496c28794481a5fa8f31
https://github.com/Albo90/python-pyodata/commit/e5b6ec1759917186a4995b9241c57b6fe2afdacb

**Few high-level questions:**

1. "we can make a reasoning to build other ways of integration" - do you have an alternative idea to compare with the code?
2. Proposal (open for discussion) - wouldn't be more maintainable in the future, instead of directly modify client.py and service.py to slap `async` variant inside, create an adapter kind of new modules e.g. async_client/async_service? Imagine in the future `pyodata.v4` module and the all four sync/async + v2/v4 combinations. 
3. There is no new test code in the three commits. Could you pls elaborate how would you like to approach unit testing of this new feature? From what I see, `pytest-asyncio` seems to be the choice, but I franky only started few weeks ago to look into the asyncio library itself, so I am not an educated one. Note: I also want to create a dockerized true odata v2/v4 test service as a target for integration testing, but that will take some time and is different use case anyway. 

**Feature work and Releases**

I would at the moment not go into creating PR to master, but rather create new "async" feature branch and do all the needful there there, so pyodata is not stuck in situation where we must release a bugfix with half-baked async feature.. so far there was no need for maintenance branches and we do a flat versioning "from master".

**Comment by phanak-sap** [comment]
Created new feature branch https://github.com/SAP/python-pyodata/tree/async

**Comment by phanak-sap** [comment]
Hi @liyakun,
 yes. But basically all I want is to move the initialization form tests to docs :) The feature itself is finished and released, so feel free to try it. Take https://github.com/SAP/python-pyodata/tree/master/tests/integration/networking_libraries as inspiration for initiliazation.

**Comment by liyakun** [comment]
@phanak-sap thanks a lot, I will have a try.

**Comment by phanak-sap** [comment]
support tasks finally done.
