### ISSUE TITLE
AttributeError: 'list' object has no attribute 'next_url'

### ISSUE THREAD

**Issue by Ndz85** [SAP/python-pyodata#238]
I get this error when following the next_url code. V3

```
jobs = service.entity_sets.Jobs.get_entities().select('Location').execute()
while True:
    for job in jobs:
     print(job.Location)

    
    # Stop if server has no more entities left
    if jobs.next_url is None:
        break
    
    
    # We got a partial answer - continue with next page
    jobs = service.entity_sets.Jobs.get_entities().next_url(jobs.next_url).execute()
```

**Comment by phanak-sap** [comment]
V3 is the problem, pyodata at the moment supports only V2 odata protocol.  Lots of things are backward compatible with V2, but some incompatible changes are there.

Out of curiosity, could you paste the $metadata for the service and the json response for the: 
`service.entity_sets.Jobs.get_entities().select('Location').execute()`

Since it got trough the initial metadata parsing, I would like to check if you by accident uncover bug that would be present in odata V2 service as well.

**Comment by phanak-sap** [comment]
Hi @Ndz85 I am closing this issue due impossibility to reproduce and inactivity from your side. If you return to this with code that reproduces the problem, please reopen.
