### ISSUE TITLE
Change service set kwargs logging from INFO to DEBUG 

### ISSUE THREAD

**Issue by ignaciocabeza** [SAP/python-pyodata#242]
Hi, full kwargs content is logged as INFO level causing logging of the full content of files sent to SAP.

Example:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/479689/216852971-5e568eba-c15b-4471-b30a-b55dcad93aae.png">

I'm pretty sure the culprit is:
- https://github.com/SAP/python-pyodata/blob/master/pyodata/v2/service.py#L537
- https://github.com/SAP/python-pyodata/blob/master/pyodata/v2/service.py#L611

```
self._logger.info(kwargs)
```

Is there any possibility to change this logging to DEBUG? or, Is there a workaround to avoid logging the full content?

For now, we set the whole pyodata module to WARNING level but maybe by doing this we are losing other important logging from pyodata.

Happy to raise a PR.

Cheers

**Comment by phanak-sap** [comment]
Hi @ignaciocabeza , I understand the pain you described. 

It is true that logging is very simple here. It is also true that maybe others are in opposite position than you, relying on the INFO logger since it is there basically from the start, six year ago. Switching to DEBUG would solve your case but would be an isolated, however backward incompatible change, even that it sounds logical and I personally don't know why the HTTP traffic itself is set as debug, while the kwarg setter with somehow similar data is set as info.

We could argue that perhaps entire logging could be improved across the library, at least more structured logger hierarchy, so you would not be stuck with `pyodata.service` logger, essentially 1:1 to python module, not allowing any meaningful granular configuration. But it seems to me as quite big feature and perhaps even for 2.X version, since there could be a necessity of some migrations.

By any chance (didn't tried it, just an idea), would it be possible to workaround this on your side by custom [logging Formatter](https://docs.python.org/3/library/logging.html#formatter-objects)? E.g. not log in the end the message, while it would stay as INFO level? Perhaps the message could have a prefix as PR to grab it more easily.

**Comment by phanak-sap** [comment]
With some time googling around python logging in general and the specific situation, I have came upon this:
https://github.com/mne-tools/mne-python/issues/4813

Maybe the proposed solutions in the issue will be applicable for you without such hard fix.

**Comment by ignaciocabeza** [comment]
Thanks @phanak-sap for your investigation!. 

It seems filtering that particular logging is the way to go. It worked!.

You can close it as probably there is no need to change logging in pyodata.

**Comment by phanak-sap** [comment]
Happy it is solved.
