### ISSUE TITLE
using pyodata to get json output structure format same as browser results

### ISSUE THREAD

**Issue by ashdsi** [SAP/python-pyodata#269]
From the browser, when I access the URL https://services.odata.org/V2/Northwind/Northwind.svc/Customers?$format=json, I get the JSON response with `results` and `_next`  objects. I'm expecting to get a similar output in python v3.9 but the output format is different. 

How should I pass the parameter for format=json and where, so I can get the same output structure as what the browser returns with `_results` field

Here's the example python script and it's response
```
import pyodata
import requests

SERVICE_URL = 'https://services.odata.org/V2/Northwind/Northwind.svc/Customers'

northwind = pyodata.Client(SERVICE_URL, requests.Session())

theservicedata = getattr(northwind.entity_sets, 'Customers')

data = theservicedata.get_entities().count(inline=True).execute()

for each in data:
    print(vars(each))
```
Sample Output
```
{
   "_logger":"<Logger pyodata.service (WARNING)>",
   "_service":<pyodata.v2.service.Service object at 0x7ff5fed4e8e0>,
   "_entity_set":"EntitySet(Customers)",
   "_entity_type":"EntityType(Customer)",
   "_key_props":[
      "StructTypeProperty(CustomerID)"
   ],
   "_cache":{
      "CustomerID":"ERNSH",
      "CompanyName":"Ernst Handel",
      "ContactName":"Roland Mendel",
      "ContactTitle":"Sales Manager",
      "Address":"Kirchgasse 6",
      "City":"Graz",
      "Region":"",
      "PostalCode":"8010",
      "Country":"Austria",
      "Phone":"7675-3425",
      "Fax":"7675-3426",
      "Orders":[
         
      ],
      "CustomerDemographics":[
         
      ]
   },
   "_entity_key":"(""ERNSH"")",
   "_etag":"None"
}
```

**Comment by phanak-sap** [comment]
Hi @ashdsi 

for quite easy question it is not an easy answer. It the end, it would depend on the question why exactly you want to have the JSON response from odata api at hand. I will point out some generic recommendation since there is no one good answere here.

- pyodata library was created to NOT work with URLs and JSONs, but wrap odata service from its metadata as python objects api. So if your case is really to request some specific URL, get repsonse as JSON and work later with just the JSON, use a HTTP library, like requests. Pyodata is a wrapper library, so you do not need to handle exactly this in a python code working with some odata APi. 
- your script is dropping everything that is in the pyodata python object for the odata api response, that is not the raw JSON from the response. print(vars(each)) - this is also not quite the expected usage of pyodata.
- have you read the Documentation? Generic how to query and what data to expect? For the specifics of working with _next keys, it is here - https://github.com/SAP/python-pyodata/blob/master/docs/usage/querying.rst#query-server-side-paginations-using-the-__next-field
- you may also reference first the tests for the service.py module. JSON response is basically an input, which is transformed by pyodata to tree of objects, referenceable by the "dot notation".
- the JSON response is within the library stored here - https://github.com/SAP/python-pyodata/blob/9f2dae53869e117d67e83ebcbe38cb8dee32f156/pyodata/v2/service.py#L141. But this is where it is store AFTER returned by the HTTP networking library of your choice, e.g. mostly Requests, like in your case. This is more important for inner workings of the library and the end API for a python programmer should be the parsed objects. Or again, probably better to use the HTTP networking library directly, if such parsed objects from JSON are for no use to you.

**Comment by phanak-sap** [comment]
Hi @ashdsi
 I am closing this since no response for a week and this is essentially a generic question issue.  Feel free to reopen if necessary.
