### ISSUE TITLE
Remove dependency on requests in service.py

### ISSUE THREAD

**Issue by phanak-sap** [SAP/python-pyodata#90]
While mainly used in tests, requests package is imported and used in service.py as well, even that it is just for status code checks.

example:   https://github.com/SAP/python-pyodata/blob/8937eca8a36aa49b5dc34e2b8de08a7671b69ccc/pyodata/v2/service.py#L840

We want no hard dependency on requests.

**Comment by mamiksik** [comment]
I believe you need to pass the requests.Session instance when initialising the client.

**Comment by phanak-sap** [comment]
> I believe you need to pass the requests.Session instance when initialising the client.

We actually require anything that conform to the requests.Session interface, does not need to be exactly the requests.Session instance. Only other thing is the if check against status codes - so it actually expect that developer has requests package installed even that it is not part of explicit dependencies (e.g. lxml).

to cite jfilak from PR #89 
> My idea was to not have a hard dependency on requests and the import in service.py is wrong.

**Comment by filak-sap** [comment]
> I believe you need to pass the requests.Session instance when initialising the client.

@mamiksik  yes, you are right and it does not contradict my goal to not have a direct dependency on requests - since we are in Python, it does not need to be requests.Session but something that implements its interface.

**Comment by filak-sap** [comment]
Have a look at the first paragraph at https://github.com/SAP/python-pyodata/blob/master/docs/usage/initialization.rst

**Comment by filak-sap** [comment]
We don't need to depend on request just to consume few constants for 404 and 201 - that's the same as you wanted to introduce the dependency on numpy only to have constants for signed int 32 max whih is "2^32 - 1".

**Comment by mamiksik** [comment]
> Have a look at the first paragraph at https://github.com/SAP/python-pyodata/blob/master/docs/usage/initialization.rst

Yes, I have read that. By then what about the type of response: 
`def get_entity_handler(parent, nav_property, navigation_entity_set, response):`?

Because, from what I can tell, it is requested .model.responses. Hence, should not then the documentation rather say "PyOData requires an external HTTP library which has API compatible with Requests." or being compatible with Session means its compatible with responses too?

**Comment by filak-sap** [comment]
Since the response is provided by requests.Session.request(), then the response must have the same interface as requests' response object. However, you can open a PR explicitly mentioning that fact.

I do understand that it's quite unrealistic anyone will be able to mimic complete requests interface or will ever want to that. But I still want to have indirect dependency on requests. That's my gut feeling - I came from C++/C world where dependencies are the worst evil and you try to hide all implementation details.

**Comment by phanak-sap** [comment]
1.  "PyOData requires an external HTTP library" - more like "PyOdata is most often used with HTTP library"; after introduction of feature "support reading metadata from local file" is valid use case just metadata validation without any networking calls. Just note for documentation PR, not a argument pro/against  :)
2. c++/java etc. have interface keyword. Here we have duck-typing so it is "same interface as requests' response object" but not explicitly stated. Having requests package really as dependency is not ideal, even as >= since it is really not needed. 
2.a - so we either need to define really an interface for request-session-like using abc.ABCMeta and @abc.abstractmethod 
2.b - or just mention thoroughly in documentation since target user is python developer and README + pytest is enought to understand basics of usage.
3. currently we do NOT have explicit dependency while we HAVE explicit usage of this package package in code, so that is obviously bad.
